In [1]:
import pandas as pd
import numpy as np
youtube_no_outliers_clean_final = pd.read_csv('../data/youtube_no_outliers_clean_final.csv', sep = ',')
youtube_no_outliers_clean_final

,duration,bitrate,bitrate(video),height,width,frame rate,frame rate(est.),codec,category,title,...,bitrate(video)_log,height_log,width_log,frame rate_log,frame rate(est.)_log,views_log,likes_log,comments_log,likes_log_win,comments_log_win
0,180,5777.0,5640.0,1920,1080,25.00,25.00,h264,News & Politics,«السودان ينتفض» أمام السفارة بالقاهرة,...,8.637817,7.560601,6.985642,3.258097,3.258097,8.313607,3.737670,1.386294,3.737670,1.386294
1,930,1195.0,1001.0,1280,720,30.00,30.00,h264,Gaming,Pokemon Tower Defense Episodio 2,...,6.909753,7.155396,6.580639,3.433987,3.433987,3.526361,1.098612,0.693147,1.098612,0.693147
2,233,3028.0,2833.0,1280,720,23.98,23.98,h264,Comedy,New Hip Hop - Kemo Treats - Pancakes,...,7.949444,7.155396,6.580639,3.218076,3.218076,9.490091,4.912655,2.890372,4.023595,1.732868
3,562,431.0,300.0,320,240,29.97,0.00,h264,People & Blogs,Sister's Keeper Impression,...,5.707110,5.771441,5.484797,3.433019,0.000000,3.784190,0.693147,0.000000,0.693147,0.000000
4,300,3087.0,2929.0,1280,720,23.98,23.98,h264,Gaming,JBHAMMER777 (AKUMA) VS KtossPol Rank 1 (Vega)...,...,7.982758,7.155396,6.580639,3.218076,3.218076,5.407172,1.098612,0.000000,1.098612,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,571,1285.0,1175.0,640,480,29.92,0.00,h264,People & Blogs,rentero 1ª parte 2.MOD,...,7.069874,6.463029,6.175867,3.431403,0.000000,3.332205,0.000000,0.000000,0.000000,0.000000
17582,105,840.0,719.0,640,480,29.97,0.00,h264,People & Blogs,Cascavel faz campanha impecável em campeonato ...,...,6.579251,6.463029,6.175867,3.433019,0.000000,5.690359,0.693147,0.000000,0.693147,0.000000
17583,161,920.0,820.0,640,480,29.97,0.00,h264,People & Blogs,Marcha para Cristo.San Francisco Menéndez. 5 ...,...,6.710523,6.463029,6.175867,3.433019,0.000000,6.647688,1.386294,0.000000,1.386294,0.000000
17584,291,4892.0,4738.0,1920,1080,29.97,29.97,h264,Gaming,DK Solo Steinerne Kern,...,8.463581,7.560601,6.985642,3.433019,3.433019,3.761200,0.693147,0.000000,0.693147,0.000000
17585,244,392.0,302.0,320,240,25.00,0.00,h264,People & Blogs,&#x202b;يارب نور دربي لعبد المجيد الفوزان بجود...,...,5.713733,5.771441,5.484797,3.258097,0.000000,3.044522,0.000000,0.000000,0.000000,0.000000

In [2]:
df = youtube_no_outliers_clean_final

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17586 entries, 0 to 17585
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   duration              17586 non-null  int64
 1   bitrate               17586 non-null  float64
 2   bitrate(video)        17586 non-null  float64
 3   height                17586 non-null  int64
 4   width                 17586 non-null  int64
 5   frame rate            17586 non-null  float64
 6   frame rate(est.)      17586 non-null  float64
 7   codec                 17586 non-null  object
 8   category              17586 non-null  object
 9   title                 17586 non-null  object
 10  description           17586 non-null  object
 11  hashtags              17586 non-null  object
 12  views                 17586 non-null  int64
 13  likes                 17586 non-null  int64
 14  comments              17586 non-null  int64
 15  duration_log          17586 non-null  float64
 16  bitrate_log           17586 non-null  float64
 17  bitrate(video)_log    17586 non-null  float64
 18  height_log            17586 non-null  float64
 19  width_log             17586 non-null  float64
 20  frame rate_log        17586 non-null  float64
 21  frame rate(est.)_log  17586 non-null  float64
 22  views_log             17586 non-null  float64
 23  likes_log             17586 non-null  float64
 24  comments_log          17586 non-null  float64
 25  likes_log_win         17586 non-null  float64
 26  comments_log_win      17586 non-null  float64
dtypes: float64(16), int64(6), object(5)
memory usage: 3.6+ MB

In [4]:
df.dtypes

duration                  int64
bitrate                 float64
bitrate(video)          float64
height                    int64
width                     int64
frame rate              float64
frame rate(est.)        float64
codec                    object
category                 object
title                    object
description              object
hashtags                 object
views                     int64
likes                     int64
comments                  int64
duration_log            float64
bitrate_log             float64
bitrate(video)_log      float64
height_log              float64
width_log               float64
frame rate_log          float64
frame rate(est.)_log    float64
views_log               float64
likes_log               float64
comments_log            float64
likes_log_win           float64
comments_log_win        float64
dtype: object

Xoá đi cột frame(est.) như đã phân tích

In [5]:
df.drop(columns=['frame rate(est.)', 'frame rate(est.)_log'], inplace=True)

Xoá đi cột birate và birate(video) như đã phân tích, giữ lại duy nhất 1 cột birate_log

In [6]:
df.drop(columns=['bitrate', 'bitrate(video)_log', 'bitrate(video)'], inplace=True)

In [7]:
print("Cột codec:")
print(df['codec'].value_counts(dropna=False))
print("\nTổng số giá trị duy nhất codec:", df['codec'].nunique())

print("\nCột category:")
print(df['category'].value_counts(dropna=False))
print("\nTổng số giá trị duy nhất category:", df['category'].nunique())

print("Cột hashtags:")
print(df['hashtags'].value_counts(dropna=False).head(10))
print("\nTổng số hashtags duy nhất:", df['hashtags'].nunique())

Cột codec:
codec
h264     17528
vp8         47
flv1         9
mpeg4        2
Name: count, dtype: int64

Tổng số giá trị duy nhất codec: 4

Cột category:
category
People & Blogs          3945
Music                   2966
Entertainment           2250
Gaming                  1420
Sports                  1230
Comedy                  1176
Autos & Vehicles         798
Education                644
News & Politics          636
Travel & Events          590
Film & Animation         587
Pets & Animals           476
Howto & Style            340
Science & Technology     283
Nonprofits & Activis     227
Shows                     18
Name: count, dtype: int64

Tổng số giá trị duy nhất category: 16
Cột hashtags:
hashtags
No hashtags                 1576
mobile                       282
YouTube Capture               39
YouTube editor                36
FlipShare                     33
video, cellphone, mobile      32
webcam, video                 23
Movie                         17
none                          14
Socialcam                     13
Name: count, dtype: int64

Tổng số hashtags duy nhất: 15108

Loại bỏ hoàn toàn các codec không phải h264
Vì 99.7% là h264, biến này không có thông tin hữu ích

In [8]:
df = df[df['codec'] == 'h264'].copy()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17528 entries, 0 to 17585
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   duration          17528 non-null  int64
 1   height            17528 non-null  int64
 2   width             17528 non-null  int64
 3   frame rate        17528 non-null  float64
 4   codec             17528 non-null  object
 5   category          17528 non-null  object
 6   title             17528 non-null  object
 7   description       17528 non-null  object
 8   hashtags          17528 non-null  object
 9   views             17528 non-null  int64
 10  likes             17528 non-null  int64
 11  comments          17528 non-null  int64
 12  duration_log      17528 non-null  float64
 13  bitrate_log       17528 non-null  float64
 14  height_log        17528 non-null  float64
 15  width_log         17528 non-null  float64
 16  frame rate_log    17528 non-null  float64
 17  views_log         17528 non-null  float64
 18  likes_log         17528 non-null  float64
 19  comments_log      17528 non-null  float64
 20  likes_log_win     17528 non-null  float64
 21  comments_log_win  17528 non-null  float64
dtypes: float64(11), int64(6), object(5)
memory usage: 3.1+ MB

# Data Preprocessing

In [10]:
from sklearn.preprocessing import StandardScaler

numerical_log_cols = [
    'duration_log', 'height_log', 'width_log', 'frame rate_log', 'bitrate_log',
    'views_log', 'likes_log', 'comments_log',
    'likes_log_win', 'comments_log_win',
]

df_norm = df.copy()

scaler = StandardScaler()

# Fit + transform
df_norm[[f'{col}_scaled' for col in numerical_log_cols]] = scaler.fit_transform(
    df[numerical_log_cols]
)

In [11]:
df_norm[[f'{c}_scaled' for c in numerical_log_cols]].describe().T

,count,mean,std,min,25%,50%,75%,max
duration_log_scaled,17528.0,-5.513111e-17,1.000029,-3.334836,-0.673920,0.111273,0.665273,4.101372
height_log_scaled,17528.0,-4.175371e-17,1.000029,-2.986006,-0.692160,-0.009694,0.670588,2.338087
width_log_scaled,17528.0,-1.014250e-15,1.000029,-3.168110,-0.644664,0.150895,0.947135,2.899273
frame rate_log_scaled,17528.0,-4.333468e-16,1.000029,-4.533019,-0.072498,0.522116,0.522116,2.774693
bitrate_log_scaled,17528.0,-4.125712e-16,1.000029,-3.415191,-0.740456,-0.134485,0.494496,3.749377
views_log_scaled,17528.0,2.270105e-17,1.000029,-2.161746,-0.680600,-0.127983,0.541290,5.856405
likes_log_scaled,17528.0,8.512892e-18,1.000029,-0.702825,-0.702825,-0.261813,0.321172,7.974002
comments_log_scaled,17528.0,2.391717e-17,1.000029,-0.449268,-0.449268,-0.449268,0.213967,8.850568
likes_log_win_scaled,17528.0,-7.053539e-17,1.000029,-0.808993,-0.808993,-0.248014,0.493559,2.447387
comments_log_win_scaled,17528.0,1.013440e-17,1.000029,-0.556978,-0.556978,-0.556978,0.597219,2.328514

In [12]:
df_norm.shape

(17528, 32)

In [13]:
df['has_description'] = df['description'].astype(str).str.strip().apply(
    lambda x: 0 if x.lower() in ['none', 'no description', '', ' '] else 1
)

df['has_hashtags'] = df['hashtags'].astype(str).str.strip().apply(
    lambda x: 0 if x.lower() in ['no hashtags', 'none', '', ' '] else 1
)

In [14]:
df[['has_description', 'has_hashtags']].value_counts(normalize=True) * 100

has_description  has_hashtags
1                1               70.903697
0                1               20.059334
1                0                4.860794
0                0                4.176175
Name: proportion, dtype: float64

In [15]:
df_encode = df[['codec', 'category', 'has_description', 'has_hashtags']].copy()

df_encode

      codec         category  has_description  has_hashtags
0      h264  News & Politics                1             1
1      h264           Gaming                1             1
2      h264           Comedy                1             1
3      h264   People & Blogs                1             1
4      h264           Gaming                1             1
...     ...              ...              ...           ...
17581  h264   People & Blogs                0             1
17582  h264   People & Blogs                0             0
17583  h264   People & Blogs                0             1
17584  h264           Gaming                1             1
17585  h264   People & Blogs                0             1

[17528 rows x 4 columns]

In [16]:
df_encode = pd.concat([df_encode,
                       pd.get_dummies(df['category'], prefix='cat', drop_first=True)
                      ], axis=1)

df_encode

,codec,category,has_description,has_hashtags,cat_Comedy,cat_Education,cat_Entertainment,cat_Film & Animation,cat_Gaming,cat_Howto & Style,cat_Music,cat_News & Politics,cat_Nonprofits & Activis,cat_People & Blogs,cat_Pets & Animals,cat_Science & Technology,cat_Shows,cat_Sports,cat_Travel & Events
0,h264,News & Politics,1,1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,h264,Gaming,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,h264,Comedy,1,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,h264,People & Blogs,1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,h264,Gaming,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,h264,People & Blogs,0,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17582,h264,People & Blogs,0,0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17583,h264,People & Blogs,0,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17584,h264,Gaming,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
17585,h264,People & Blogs,0,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [17]:
df_model = pd.concat([df_norm, df_encode], axis=1)

df_model

,duration,height,width,frame rate,codec,category,title,description,hashtags,views,...,cat_Howto & Style,cat_Music,cat_News & Politics,cat_Nonprofits & Activis,cat_People & Blogs,cat_Pets & Animals,cat_Science & Technology,cat_Shows,cat_Sports,cat_Travel & Events
0,180,1920,1080,25.00,h264,News & Politics,«السودان ينتفض» أمام السفارة بالقاهرة,حرية سلام وعدالة، الثورة خيار الشعب.. بهذا اله...,"في, عسكري, حكم, حرية, بخصوص, المصري اليوم, الس...",4078,...,False,False,True,False,False,False,False,False,False,False
1,930,1280,720,30.00,h264,Gaming,Pokemon Tower Defense Episodio 2,Espero que tenham gostado do video!,"Pokémon (Anime/Manga Franchise), Pokémon (Vide...",33,...,False,False,False,False,False,False,False,False,False,False
2,233,1280,720,23.98,h264,Comedy,New Hip Hop - Kemo Treats - Pancakes,Download all our music for FREE just enter $0....,"breaking bad spoof, Recipes, Pancakes, canada,...",13227,...,False,False,False,False,False,False,False,False,False,False
3,562,320,240,29.97,h264,People & Blogs,Sister's Keeper Impression,A Review of the Shampoo Bar(Sunburst) and Dip ...,"natural hair, first impression, sister's keepe...",43,...,False,False,False,False,True,False,False,False,False,False
4,300,1280,720,23.98,h264,Gaming,JBHAMMER777 (AKUMA) VS KtossPol Rank 1 (Vega)...,JBHAMMER777 is he strong enough to fight again...,"Tokido, momochi, (Ryu), AE, 11, at, Piyoppia, ...",222,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,571,640,480,29.92,h264,People & Blogs,rentero 1ª parte 2.MOD,No description,"rentero, latapialinares, iu, pca",27,...,False,False,False,False,True,False,False,False,False,False
17582,105,640,480,29.97,h264,People & Blogs,Cascavel faz campanha impecável em campeonato ...,No description,No hashtags,295,...,False,False,False,False,True,False,False,False,False,False
17583,161,640,480,29.97,h264,People & Blogs,Marcha para Cristo.San Francisco Menéndez. 5 ...,No description,"Cristo, Marcha, para",770,...,False,False,False,False,True,False,False,False,False,False
17584,291,1920,1080,29.97,h264,Gaming,DK Solo Steinerne Kern,"Das ist mein erstes Video, also ist noch alles...","Steinerne Kern, Vitriolsteindrachen, DK Solo, ...",42,...,False,False,False,False,False,False,False,False,False,False
17585,244,320,240,25.00,h264,People & Blogs,&#x202b;يارب نور دربي لعبد المجيد الفوزان بجود...,No description,"نور, بجوده, دربي, &#x202b;يارب, المجيد, عاليه&...",20,...,False,False,False,False,True,False,False,False,False,False

Xử Lý Height × Width Multicollinearity

In [18]:
df_model['resolution_score_log'] = np.log1p(
    np.sqrt(np.expm1(df_model['height_log']) * np.expm1(df_model['width_log']))
)

df_model['resolution_score_scaled'] = (
    df_model['resolution_score_log'] / df_model['resolution_score_log'].max()
)

cols_to_drop = ['height_log', 'width_log', 'height_log_scaled', 'width_log_scaled', 'resolution_score_log']
df_model = df_model.drop(columns=cols_to_drop, errors='ignore')

In [19]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17528 entries, 0 to 17585
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   duration                  17528 non-null  int64
 1   height                    17528 non-null  int64
 2   width                     17528 non-null  int64
 3   frame rate                17528 non-null  float64
 4   codec                     17528 non-null  object
 5   category                  17528 non-null  object
 6   title                     17528 non-null  object
 7   description               17528 non-null  object
 8   hashtags                  17528 non-null  object
 9   views                     17528 non-null  int64
 10  likes                     17528 non-null  int64
 11  comments                  17528 non-null  int64
 12  duration_log              17528 non-null  float64
 13  bitrate_log               17528 non-null  float64
 14  frame rate_log            17528 non-null  float64
 15  views_log                 17528 non-null  float64
 16  likes_log                 17528 non-null  float64
 17  comments_log              17528 non-null  float64
 18  likes_log_win             17528 non-null  float64
 19  comments_log_win          17528 non-null  float64
 20  duration_log_scaled       17528 non-null  float64
 21  frame rate_log_scaled     17528 non-null  float64
 22  bitrate_log_scaled        17528 non-null  float64
 23  views_log_scaled          17528 non-null  float64
 24  likes_log_scaled          17528 non-null  float64
 25  comments_log_scaled       17528 non-null  float64
 26  likes_log_win_scaled      17528 non-null  float64
 27  comments_log_win_scaled   17528 non-null  float64
 28  codec                     17528 non-null  object
 29  category                  17528 non-null  object
 30  has_description           17528 non-null  int64
 31  has_hashtags              17528 non-null  int64
 32  cat_Comedy                17528 non-null  bool
 33  cat_Education             17528 non-null  bool
 34  cat_Entertainment         17528 non-null  bool
 35  cat_Film & Animation      17528 non-null  bool
 36  cat_Gaming                17528 non-null  bool
 37  cat_Howto & Style         17528 non-null  bool
 38  cat_Music                 17528 non-null  bool
 39  cat_News & Politics       17528 non-null  bool
 40  cat_Nonprofits & Activis  17528 non-null  bool
 41  cat_People & Blogs        17528 non-null  bool
 42  cat_Pets & Animals        17528 non-null  bool
 43  cat_Science & Technology  17528 non-null  bool
 44  cat_Shows                 17528 non-null  bool
 45  cat_Sports                17528 non-null  bool
 46  cat_Travel & Events       17528 non-null  bool
 47  resolution_score_scaled   17528 non-null  float64
dtypes: bool(15), float64(18), int64(8), object(7)
memory usage: 4.8+ MB

# Feature engineering

In [20]:
df_model['aspect_ratio'] = df_model['width'] / df_model['height']

df_model['is_hd'] = (df_model['height'] >= 720).astype(int)
df_model['is_full_hd'] = (df_model['height'] >= 1080).astype(int)
df_model['is_4k'] = (df_model['height'] >= 2160).astype(int)

df_model['is_short'] = (df_model['duration'] < 60).astype(int)
df_model['is_medium'] = ((df_model['duration'] >= 60) & (df_model['duration'] < 600)).astype(int)
df_model['is_long'] = (df_model['duration'] >= 600).astype(int)

df_model['content_score'] = df_model['has_description'] + df_model['has_hashtags']

df_model['duration_bitrate_ratio'] = (
    df_model['duration_log_scaled'] / (df_model['bitrate_log_scaled'] + 0.01)
)

df_model['optimal_duration'] = (
    (df_model['duration'] >= 120) & (df_model['duration'] <= 600)
).astype(int)

df_model['content_completeness'] = (
    0.6 * df_model['has_description'] +
    0.4 * df_model['has_hashtags']
)


# Category popularity (từ ANOVA analysis)
# Music, Entertainment, Comedy, Gaming có views cao hơn
popular_cats = ['Music', 'Entertainment', 'Comedy', 'Gaming']
df_model['is_popular_category'] = df_model[[f'cat_{c}' for c in popular_cats]].max(axis=1)

# Frame rate category
# 24fps (cinema), 30fps (standard), 60fps (high)
df_model['is_high_fps'] = (df_model['frame rate'] >= 50).astype(int)
df_model['is_cinema_fps'] = (
    (df_model['frame rate'] >= 23) & (df_model['frame rate'] <= 25)
).astype(int)

In [21]:
cols_to_drop = [
    'duration', 'height', 'width', 'frame rate',
    'codec', 'category', 'description', 'hashtags', 'title',
    'duration_log', 'frame rate_log',
    'bitrate_log'
]
df_model = df_model.drop(columns=cols_to_drop)

In [22]:
rename_dict = {
    'duration_log_scaled': 'duration_scaled',
    'frame rate_log_scaled': 'framerate_scaled',
    'bitrate_log_scaled': 'bitrate_scaled'
}
df_model = df_model.rename(columns=rename_dict)

In [23]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17528 entries, 0 to 17585
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   views                     17528 non-null  int64
 1   likes                     17528 non-null  int64
 2   comments                  17528 non-null  int64
 3   views_log                 17528 non-null  float64
 4   likes_log                 17528 non-null  float64
 5   comments_log              17528 non-null  float64
 6   likes_log_win             17528 non-null  float64
 7   comments_log_win          17528 non-null  float64
 8   duration_scaled           17528 non-null  float64
 9   framerate_scaled          17528 non-null  float64
 10  bitrate_scaled            17528 non-null  float64
 11  views_log_scaled          17528 non-null  float64
 12  likes_log_scaled          17528 non-null  float64
 13  comments_log_scaled       17528 non-null  float64
 14  likes_log_win_scaled      17528 non-null  float64
 15  comments_log_win_scaled   17528 non-null  float64
 16  has_description           17528 non-null  int64
 17  has_hashtags              17528 non-null  int64
 18  cat_Comedy                17528 non-null  bool
 19  cat_Education             17528 non-null  bool
 20  cat_Entertainment         17528 non-null  bool
 21  cat_Film & Animation      17528 non-null  bool
 22  cat_Gaming                17528 non-null  bool
 23  cat_Howto & Style         17528 non-null  bool
 24  cat_Music                 17528 non-null  bool
 25  cat_News & Politics       17528 non-null  bool
 26  cat_Nonprofits & Activis  17528 non-null  bool
 27  cat_People & Blogs        17528 non-null  bool
 28  cat_Pets & Animals        17528 non-null  bool
 29  cat_Science & Technology  17528 non-null  bool
 30  cat_Shows                 17528 non-null  bool
 31  cat_Sports                17528 non-null  bool
 32  cat_Travel & Events       17528 non-null  bool
 33  resolution_score_scaled   17528 non-null  float64
 34  aspect_ratio              17528 non-null  float64
 35  is_hd                     17528 non-null  int64
 36  is_full_hd                17528 non-null  int64
 37  is_4k                     17528 non-null  int64
 38  is_short                  17528 non-null  int64
 39  is_medium                 17528 non-null  int64
 40  is_long                   17528 non-null  int64
 41  content_score             17528 non-null  int64
 42  duration_bitrate_ratio    17528 non-null  float64
 43  optimal_duration          17528 non-null  int64
 44  content_completeness      17528 non-null  float64
 45  is_popular_category       17528 non-null  bool
 46  is_high_fps               17528 non-null  int64
 47  is_cinema_fps             17528 non-null  int64
dtypes: bool(16), float64(17), int64(15)
memory usage: 4.7 MB

In [24]:
df_model.to_csv("../data/final_youtube_v2.csv")