In [1]:
import pandas as pd
import numpy as np
youtube_no_outliers_clean_final = pd.read_csv('../data/youtube_no_outliers_clean_final.csv', sep = ',')
youtube_no_outliers_clean_final

,duration,bitrate,bitrate(video),height,width,frame rate,frame rate(est.),codec,category,title,...,bitrate(video)_log,height_log,width_log,frame rate_log,frame rate(est.)_log,views_log,likes_log,comments_log,likes_log_win,comments_log_win
0,180,5777.0,5640.0,1920,1080,25.00,25.00,h264,News & Politics,«السودان ينتفض» أمام السفارة بالقاهرة,...,8.637817,7.560601,6.985642,3.258097,3.258097,8.313607,3.737670,1.386294,3.737670,1.386294
1,930,1195.0,1001.0,1280,720,30.00,30.00,h264,Gaming,Pokemon Tower Defense Episodio 2,...,6.909753,7.155396,6.580639,3.433987,3.433987,3.526361,1.098612,0.693147,1.098612,0.693147
2,233,3028.0,2833.0,1280,720,23.98,23.98,h264,Comedy,New Hip Hop - Kemo Treats - Pancakes,...,7.949444,7.155396,6.580639,3.218076,3.218076,9.490091,4.912655,2.890372,4.023595,1.732868
3,562,431.0,300.0,320,240,29.97,0.00,h264,People & Blogs,Sister's Keeper Impression,...,5.707110,5.771441,5.484797,3.433019,0.000000,3.784190,0.693147,0.000000,0.693147,0.000000
4,300,3087.0,2929.0,1280,720,23.98,23.98,h264,Gaming,JBHAMMER777 (AKUMA) VS KtossPol Rank 1 (Vega)...,...,7.982758,7.155396,6.580639,3.218076,3.218076,5.407172,1.098612,0.000000,1.098612,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,571,1285.0,1175.0,640,480,29.92,0.00,h264,People & Blogs,rentero 1ª parte 2.MOD,...,7.069874,6.463029,6.175867,3.431403,0.000000,3.332205,0.000000,0.000000,0.000000,0.000000
17582,105,840.0,719.0,640,480,29.97,0.00,h264,People & Blogs,Cascavel faz campanha impecável em campeonato ...,...,6.579251,6.463029,6.175867,3.433019,0.000000,5.690359,0.693147,0.000000,0.693147,0.000000
17583,161,920.0,820.0,640,480,29.97,0.00,h264,People & Blogs,Marcha para Cristo.San Francisco Menéndez. 5 ...,...,6.710523,6.463029,6.175867,3.433019,0.000000,6.647688,1.386294,0.000000,1.386294,0.000000
17584,291,4892.0,4738.0,1920,1080,29.97,29.97,h264,Gaming,DK Solo Steinerne Kern,...,8.463581,7.560601,6.985642,3.433019,3.433019,3.761200,0.693147,0.000000,0.693147,0.000000
17585,244,392.0,302.0,320,240,25.00,0.00,h264,People & Blogs,&#x202b;يارب نور دربي لعبد المجيد الفوزان بجود...,...,5.713733,5.771441,5.484797,3.258097,0.000000,3.044522,0.000000,0.000000,0.000000,0.000000

In [2]:
df = youtube_no_outliers_clean_final

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17586 entries, 0 to 17585
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   duration              17586 non-null  int64
 1   bitrate               17586 non-null  float64
 2   bitrate(video)        17586 non-null  float64
 3   height                17586 non-null  int64
 4   width                 17586 non-null  int64
 5   frame rate            17586 non-null  float64
 6   frame rate(est.)      17586 non-null  float64
 7   codec                 17586 non-null  object
 8   category              17586 non-null  object
 9   title                 17586 non-null  object
 10  description           17586 non-null  object
 11  hashtags              17586 non-null  object
 12  views                 17586 non-null  int64
 13  likes                 17586 non-null  int64
 14  comments              17586 non-null  int64
 15  duration_log          17586 non-null  float64
 16  bitrate_log           17586 non-null  float64
 17  bitrate(video)_log    17586 non-null  float64
 18  height_log            17586 non-null  float64
 19  width_log             17586 non-null  float64
 20  frame rate_log        17586 non-null  float64
 21  frame rate(est.)_log  17586 non-null  float64
 22  views_log             17586 non-null  float64
 23  likes_log             17586 non-null  float64
 24  comments_log          17586 non-null  float64
 25  likes_log_win         17586 non-null  float64
 26  comments_log_win      17586 non-null  float64
dtypes: float64(16), int64(6), object(5)
memory usage: 3.6+ MB

In [4]:
df.dtypes

duration                  int64
bitrate                 float64
bitrate(video)          float64
height                    int64
width                     int64
frame rate              float64
frame rate(est.)        float64
codec                    object
category                 object
title                    object
description              object
hashtags                 object
views                     int64
likes                     int64
comments                  int64
duration_log            float64
bitrate_log             float64
bitrate(video)_log      float64
height_log              float64
width_log               float64
frame rate_log          float64
frame rate(est.)_log    float64
views_log               float64
likes_log               float64
comments_log            float64
likes_log_win           float64
comments_log_win        float64
dtype: object

Xoá đi cột frame(est.) như đã phân tích

In [5]:
df.drop(columns=['frame rate(est.)', 'frame rate(est.)_log'], inplace=True)

Xoá đi cột birate và birate(video) như đã phân tích, giữ lại duy nhất 1 cột birate_log

In [6]:
df.drop(columns=['bitrate', 'bitrate(video)_log', 'bitrate(video)'], inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17586 entries, 0 to 17585
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   duration          17586 non-null  int64
 1   height            17586 non-null  int64
 2   width             17586 non-null  int64
 3   frame rate        17586 non-null  float64
 4   codec             17586 non-null  object
 5   category          17586 non-null  object
 6   title             17586 non-null  object
 7   description       17586 non-null  object
 8   hashtags          17586 non-null  object
 9   views             17586 non-null  int64
 10  likes             17586 non-null  int64
 11  comments          17586 non-null  int64
 12  duration_log      17586 non-null  float64
 13  bitrate_log       17586 non-null  float64
 14  height_log        17586 non-null  float64
 15  width_log         17586 non-null  float64
 16  frame rate_log    17586 non-null  float64
 17  views_log         17586 non-null  float64
 18  likes_log         17586 non-null  float64
 19  comments_log      17586 non-null  float64
 20  likes_log_win     17586 non-null  float64
 21  comments_log_win  17586 non-null  float64
dtypes: float64(11), int64(6), object(5)
memory usage: 3.0+ MB

In [8]:
numerical_log_cols = [
    'duration_log', 'height_log', 'width_log', 'frame rate_log',
    'views_log', 'likes_log', 'comments_log',
    'likes_log_win', 'comments_log_win'
]

df_norm = df.copy()

# Áp dụng 3 phương pháp chuẩn hóa
for col in numerical_log_cols:
    col_max = df[col].max()
    col_min = df[col].min()
    col_mean = df[col].mean()
    col_std = df[col].std()

    # Scale (chia tỉ lệ so với max)
    df_norm[f'{col}_scaled'] = df[col] / col_max

    # Min-Max
    df_norm[f'{col}_minmax'] = (df[col] - col_min) / (col_max - col_min)

    # Z-score
    df_norm[f'{col}_zscore'] = (df[col] - col_mean) / col_std

In [9]:
df_norm[[f'{c}_scaled' for c in numerical_log_cols]].describe().T

,count,mean,std,min,25%,50%,75%,max
duration_log_scaled,17586.0,0.470162,0.120614,0.068224,0.388905,0.483533,0.550665,1.0
height_log_scaled,17586.0,0.822949,0.075796,0.596820,0.770527,0.822209,0.873725,1.0
width_log_scaled,17586.0,0.805378,0.067181,0.592714,0.762106,0.815509,0.868959,1.0
frame rate_log_scaled,17586.0,0.800286,0.072290,0.380436,0.795496,0.838206,0.838206,1.0
views_log_scaled,17586.0,0.269669,0.124759,0.000000,0.184724,0.253973,0.337115,1.0
likes_log_scaled,17586.0,0.081011,0.115320,0.000000,0.000000,0.050826,0.118015,1.0
comments_log_scaled,17586.0,0.048327,0.107562,0.000000,0.000000,0.000000,0.071317,1.0
likes_log_win_scaled,17586.0,0.248398,0.307159,0.000000,0.000000,0.172271,0.400000,1.0
comments_log_win_scaled,17586.0,0.193041,0.346695,0.000000,0.000000,0.000000,0.400000,1.0

In [10]:
df_norm[[f'{c}_minmax' for c in numerical_log_cols]].describe().T

,count,mean,std,min,25%,50%,75%,max
duration_log_minmax,17586.0,0.431368,0.129445,0.0,0.344162,0.445718,0.517766,1.0
height_log_minmax,17586.0,0.560864,0.187995,0.0,0.430843,0.559027,0.686801,1.0
width_log_minmax,17586.0,0.522149,0.164949,0.0,0.415903,0.547024,0.678257,1.0
frame rate_log_minmax,17586.0,0.677654,0.116678,0.0,0.669923,0.738857,0.738857,1.0
views_log_minmax,17586.0,0.269669,0.124759,0.0,0.184724,0.253973,0.337115,1.0
likes_log_minmax,17586.0,0.081011,0.115320,0.0,0.000000,0.050826,0.118015,1.0
comments_log_minmax,17586.0,0.048327,0.107562,0.0,0.000000,0.000000,0.071317,1.0
likes_log_win_minmax,17586.0,0.248398,0.307159,0.0,0.000000,0.172271,0.400000,1.0
comments_log_win_minmax,17586.0,0.193041,0.346695,0.0,0.000000,0.000000,0.400000,1.0

In [11]:
df_norm[[f'{c}_zscore' for c in numerical_log_cols]].describe().T

,count,mean,std,min,25%,50%,75%,max
duration_log_zscore,17586.0,-3.248472e-16,1.0,-3.332434,-0.673694,0.110856,0.667442,4.392830
height_log_zscore,17586.0,-1.805246e-15,1.0,-2.983400,-0.691622,-0.009770,0.669898,2.335894
width_log_zscore,17586.0,2.989888e-17,1.0,-3.165525,-0.644114,0.150804,0.946402,2.896967
frame rate_log_zscore,17586.0,-1.452520e-15,1.0,-5.807889,-0.066260,0.524545,0.524545,2.762688
views_log_zscore,17586.0,1.393934e-16,1.0,-2.161522,-0.680874,-0.125810,0.540605,5.853934
likes_log_zscore,17586.0,-2.383829e-17,1.0,-0.702493,-0.702493,-0.261751,0.320878,7.969036
comments_log_zscore,17586.0,-1.050501e-17,1.0,-0.449297,-0.449297,-0.449297,0.213736,8.847697
likes_log_win_zscore,17586.0,-8.686835e-17,1.0,-0.808696,-0.808696,-0.247845,0.493560,2.446945
comments_log_win_zscore,17586.0,-3.030291e-17,1.0,-0.556803,-0.556803,-0.556803,0.596950,2.327581

In [12]:
df_norm.shape

(17586, 49)

In [13]:
print("Cột codec:")
print(df['codec'].value_counts(dropna=False).head(10))
print("\nTổng số giá trị duy nhất codec:", df['codec'].nunique())

print("\nCột category:")
print(df['category'].value_counts(dropna=False).head(10))
print("\nTổng số giá trị duy nhất category:", df['category'].nunique())

print("Cột hashtags:")
print(df['hashtags'].value_counts(dropna=False).head(10))
print("\nTổng số hashtags duy nhất:", df['hashtags'].nunique())

Cột codec:
codec
h264     17528
vp8         47
flv1         9
mpeg4        2
Name: count, dtype: int64

Tổng số giá trị duy nhất codec: 4

Cột category:
category
People & Blogs      3945
Music               2966
Entertainment       2250
Gaming              1420
Sports              1230
Comedy              1176
Autos & Vehicles     798
Education            644
News & Politics      636
Travel & Events      590
Name: count, dtype: int64

Tổng số giá trị duy nhất category: 16
Cột hashtags:
hashtags
No hashtags                 1576
mobile                       282
YouTube Capture               39
YouTube editor                36
FlipShare                     33
video, cellphone, mobile      32
webcam, video                 23
Movie                         17
none                          14
Socialcam                     13
Name: count, dtype: int64

Tổng số hashtags duy nhất: 15108

In [14]:
df['has_description'] = df['description'].astype(str).str.strip().apply(
    lambda x: 0 if x.lower() in ['none', 'no description', '', ' '] else 1
)

df['has_hashtags'] = df['hashtags'].astype(str).str.strip().apply(
    lambda x: 0 if x.lower() in ['no hashtags', 'none', '', ' '] else 1
)

In [15]:
df[['has_description', 'has_hashtags']].value_counts(normalize=True) * 100

has_description  has_hashtags
1                1               70.920050
0                1               20.038667
1                0                4.850449
0                0                4.190834
Name: proportion, dtype: float64

In [16]:
df_encode = df[['codec', 'category', 'has_description', 'has_hashtags']].copy()

df_encode

      codec         category  has_description  has_hashtags
0      h264  News & Politics                1             1
1      h264           Gaming                1             1
2      h264           Comedy                1             1
3      h264   People & Blogs                1             1
4      h264           Gaming                1             1
...     ...              ...              ...           ...
17581  h264   People & Blogs                0             1
17582  h264   People & Blogs                0             0
17583  h264   People & Blogs                0             1
17584  h264           Gaming                1             1
17585  h264   People & Blogs                0             1

[17586 rows x 4 columns]

In [17]:
df_encode['is_h264'] = (df['codec'] == 'h264').astype(int)

df_encode = pd.concat([df_encode,
                       pd.get_dummies(df['category'], prefix='cat', drop_first=True)
                      ], axis=1)

df_encode

,codec,category,has_description,has_hashtags,is_h264,cat_Comedy,cat_Education,cat_Entertainment,cat_Film & Animation,cat_Gaming,cat_Howto & Style,cat_Music,cat_News & Politics,cat_Nonprofits & Activis,cat_People & Blogs,cat_Pets & Animals,cat_Science & Technology,cat_Shows,cat_Sports,cat_Travel & Events
0,h264,News & Politics,1,1,1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,h264,Gaming,1,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,h264,Comedy,1,1,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,h264,People & Blogs,1,1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,h264,Gaming,1,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,h264,People & Blogs,0,1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17582,h264,People & Blogs,0,0,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17583,h264,People & Blogs,0,1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
17584,h264,Gaming,1,1,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
17585,h264,People & Blogs,0,1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [18]:
df_model = pd.concat([df_norm, df_encode], axis=1)

df_model

,duration,height,width,frame rate,codec,category,title,description,hashtags,views,...,cat_Howto & Style,cat_Music,cat_News & Politics,cat_Nonprofits & Activis,cat_People & Blogs,cat_Pets & Animals,cat_Science & Technology,cat_Shows,cat_Sports,cat_Travel & Events
0,180,1920,1080,25.00,h264,News & Politics,«السودان ينتفض» أمام السفارة بالقاهرة,حرية سلام وعدالة، الثورة خيار الشعب.. بهذا اله...,"في, عسكري, حكم, حرية, بخصوص, المصري اليوم, الس...",4078,...,False,False,True,False,False,False,False,False,False,False
1,930,1280,720,30.00,h264,Gaming,Pokemon Tower Defense Episodio 2,Espero que tenham gostado do video!,"Pokémon (Anime/Manga Franchise), Pokémon (Vide...",33,...,False,False,False,False,False,False,False,False,False,False
2,233,1280,720,23.98,h264,Comedy,New Hip Hop - Kemo Treats - Pancakes,Download all our music for FREE just enter $0....,"breaking bad spoof, Recipes, Pancakes, canada,...",13227,...,False,False,False,False,False,False,False,False,False,False
3,562,320,240,29.97,h264,People & Blogs,Sister's Keeper Impression,A Review of the Shampoo Bar(Sunburst) and Dip ...,"natural hair, first impression, sister's keepe...",43,...,False,False,False,False,True,False,False,False,False,False
4,300,1280,720,23.98,h264,Gaming,JBHAMMER777 (AKUMA) VS KtossPol Rank 1 (Vega)...,JBHAMMER777 is he strong enough to fight again...,"Tokido, momochi, (Ryu), AE, 11, at, Piyoppia, ...",222,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,571,640,480,29.92,h264,People & Blogs,rentero 1ª parte 2.MOD,No description,"rentero, latapialinares, iu, pca",27,...,False,False,False,False,True,False,False,False,False,False
17582,105,640,480,29.97,h264,People & Blogs,Cascavel faz campanha impecável em campeonato ...,No description,No hashtags,295,...,False,False,False,False,True,False,False,False,False,False
17583,161,640,480,29.97,h264,People & Blogs,Marcha para Cristo.San Francisco Menéndez. 5 ...,No description,"Cristo, Marcha, para",770,...,False,False,False,False,True,False,False,False,False,False
17584,291,1920,1080,29.97,h264,Gaming,DK Solo Steinerne Kern,"Das ist mein erstes Video, also ist noch alles...","Steinerne Kern, Vitriolsteindrachen, DK Solo, ...",42,...,False,False,False,False,False,False,False,False,False,False
17585,244,320,240,25.00,h264,People & Blogs,&#x202b;يارب نور دربي لعبد المجيد الفوزان بجود...,No description,"نور, بجوده, دربي, &#x202b;يارب, المجيد, عاليه&...",20,...,False,False,False,False,True,False,False,False,False,False

In [19]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17586 entries, 0 to 17585
Data columns (total 69 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   duration                  17586 non-null  int64
 1   height                    17586 non-null  int64
 2   width                     17586 non-null  int64
 3   frame rate                17586 non-null  float64
 4   codec                     17586 non-null  object
 5   category                  17586 non-null  object
 6   title                     17586 non-null  object
 7   description               17586 non-null  object
 8   hashtags                  17586 non-null  object
 9   views                     17586 non-null  int64
 10  likes                     17586 non-null  int64
 11  comments                  17586 non-null  int64
 12  duration_log              17586 non-null  float64
 13  bitrate_log               17586 non-null  float64
 14  height_log                17586 non-null  float64
 15  width_log                 17586 non-null  float64
 16  frame rate_log            17586 non-null  float64
 17  views_log                 17586 non-null  float64
 18  likes_log                 17586 non-null  float64
 19  comments_log              17586 non-null  float64
 20  likes_log_win             17586 non-null  float64
 21  comments_log_win          17586 non-null  float64
 22  duration_log_scaled       17586 non-null  float64
 23  duration_log_minmax       17586 non-null  float64
 24  duration_log_zscore       17586 non-null  float64
 25  height_log_scaled         17586 non-null  float64
 26  height_log_minmax         17586 non-null  float64
 27  height_log_zscore         17586 non-null  float64
 28  width_log_scaled          17586 non-null  float64
 29  width_log_minmax          17586 non-null  float64
 30  width_log_zscore          17586 non-null  float64
 31  frame rate_log_scaled     17586 non-null  float64
 32  frame rate_log_minmax     17586 non-null  float64
 33  frame rate_log_zscore     17586 non-null  float64
 34  views_log_scaled          17586 non-null  float64
 35  views_log_minmax          17586 non-null  float64
 36  views_log_zscore          17586 non-null  float64
 37  likes_log_scaled          17586 non-null  float64
 38  likes_log_minmax          17586 non-null  float64
 39  likes_log_zscore          17586 non-null  float64
 40  comments_log_scaled       17586 non-null  float64
 41  comments_log_minmax       17586 non-null  float64
 42  comments_log_zscore       17586 non-null  float64
 43  likes_log_win_scaled      17586 non-null  float64
 44  likes_log_win_minmax      17586 non-null  float64
 45  likes_log_win_zscore      17586 non-null  float64
 46  comments_log_win_scaled   17586 non-null  float64
 47  comments_log_win_minmax   17586 non-null  float64
 48  comments_log_win_zscore   17586 non-null  float64
 49  codec                     17586 non-null  object
 50  category                  17586 non-null  object
 51  has_description           17586 non-null  int64
 52  has_hashtags              17586 non-null  int64
 53  is_h264                   17586 non-null  int64
 54  cat_Comedy                17586 non-null  bool
 55  cat_Education             17586 non-null  bool
 56  cat_Entertainment         17586 non-null  bool
 57  cat_Film & Animation      17586 non-null  bool
 58  cat_Gaming                17586 non-null  bool
 59  cat_Howto & Style         17586 non-null  bool
 60  cat_Music                 17586 non-null  bool
 61  cat_News & Politics       17586 non-null  bool
 62  cat_Nonprofits & Activis  17586 non-null  bool
 63  cat_People & Blogs        17586 non-null  bool
 64  cat_Pets & Animals        17586 non-null  bool
 65  cat_Science & Technology  17586 non-null  bool
 66  cat_Shows                 17586 non-null  bool
 67  cat_Sports                17586 non-null  bool
 68  cat_Travel & Events       17586 non-null  bool
dtypes: bool(15), float64(38), int64(9), object(7)
memory usage: 7.5+ MB

In [20]:
cols_to_drop = [
    'duration', 'height', 'width', 'frame rate',
    'codec', 'category', 'description', 'hashtags', 'title'
]
df_model = df_model.drop(columns=cols_to_drop)

# Feature engineering

In [21]:
df_model['like_per_view_log'] = df_model['likes_log'] - df_model['views_log']
df_model['comment_per_view_log'] = df_model['comments_log'] - df_model['views_log']

# Engagement rate log: log((likes + comments)/views)
df_model['engagement_rate_log'] = np.log(np.exp(df_model['likes_log']) + np.exp(df_model['comments_log'])) - df_model['views_log']

# Tỷ lệ giữa dimension
df_model['aspect_ratio'] = df_model['width_log'] - df_model['height_log']  # log(width/height)
df_model['log_aspect_ratio'] = df_model['width_log'] - df_model['height_log']

# Kiểm tra các cột mới
df_model[['like_per_view_log', 'comment_per_view_log', 'engagement_rate_log',
          'aspect_ratio', 'log_aspect_ratio']].head()

,like_per_view_log,comment_per_view_log,engagement_rate_log,aspect_ratio,log_aspect_ratio
0,-4.575938,-6.927313,-4.484966,-0.574959,-0.574959
1,-2.427748,-2.833213,-1.916923,-0.574757,-0.574757
2,-4.577436,-6.599719,-4.453138,-0.574757,-0.574757
3,-3.091042,-3.784190,-2.685577,-0.286644,-0.286644
4,-4.308559,-5.407172,-4.020877,-0.574757,-0.574757

In [22]:
cols_to_scale = [
    'like_per_view_log',
    'comment_per_view_log',
    'engagement_rate_log',
    'aspect_ratio',
    'log_aspect_ratio'
]

for col in numerical_log_cols:
    col_max = df[col].max()
    col_min = df[col].min()
    col_mean = df[col].mean()
    col_std = df[col].std()

    # Scale (chia tỉ lệ so với max)
    df_norm[f'{col}_scaled'] = df[col] / col_max

    # Min-Max
    df_norm[f'{col}_minmax'] = (df[col] - col_min) / (col_max - col_min)

    # Z-score
    df_norm[f'{col}_zscore'] = (df[col] - col_mean) / col_std

In [23]:
numerical_log_cols = [
    'like_per_view_log',
    'comment_per_view_log',
    'engagement_rate_log',
    'aspect_ratio',
    'log_aspect_ratio'
]

df_model_norm = df_model.copy()

for col in numerical_log_cols:
    col_max = df_model[col].max()
    col_min = df_model[col].min()
    col_mean = df_model[col].mean()
    col_std = df_model[col].std()

    # Scale (chia tỉ lệ so với max)
    df_model_norm[f'{col}_scaled'] = df_model[col] / col_max

    # Min-Max
    df_model_norm[f'{col}_minmax'] = (df_model[col] - col_min) / (col_max - col_min)

    # Z-score
    df_model_norm[f'{col}_zscore'] = (df_model[col] - col_mean) / col_std

In [24]:
df_model_norm

,views,likes,comments,duration_log,bitrate_log,height_log,width_log,frame rate_log,views_log,likes_log,...,comment_per_view_log_zscore,engagement_rate_log_scaled,engagement_rate_log_minmax,engagement_rate_log_zscore,aspect_ratio_scaled,aspect_ratio_minmax,aspect_ratio_zscore,log_aspect_ratio_scaled,log_aspect_ratio_minmax,log_aspect_ratio_zscore
0,4078,41,3,5.198497,8.661813,7.560601,6.985642,3.258097,8.313607,3.737670,...,-1.059990,-2.916683,0.605412,-0.479846,-0.964474,0.329254,-0.941672,-0.964474,0.329254,-0.941672
1,33,2,1,6.836259,7.086738,7.155396,6.580639,3.433987,3.526361,1.098612,...,1.058208,-1.246622,0.773663,1.168789,-0.964135,0.329370,-0.940744,-0.964135,0.329370,-0.940744
2,13227,135,17,5.455321,8.015988,7.155396,6.580639,3.218076,9.490091,4.912655,...,-0.890500,-2.895985,0.607498,-0.459413,-0.964135,0.329370,-0.940744,-0.964135,0.329370,-0.940744
3,43,1,0,6.333280,6.068426,5.771441,5.484797,3.433019,3.784190,0.693147,...,0.566193,-1.746497,0.723303,0.675328,-0.480836,0.494386,0.381083,-0.480836,0.494386,0.381083
4,222,2,0,5.707110,8.035279,7.155396,6.580639,3.218076,5.407172,1.098612,...,-0.273502,-2.614875,0.635818,-0.181910,-0.964135,0.329370,-0.940744,-0.964135,0.329370,-0.940744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17581,27,0,0,6.349139,7.159292,6.463029,6.175867,3.431403,3.332205,0.000000,...,0.800040,-1.716243,0.726351,0.705192,-0.481705,0.494090,0.378707,-0.481705,0.494090,0.378707
17582,295,1,0,4.663439,6.734592,6.463029,6.175867,3.433019,5.690359,0.693147,...,-0.420017,-2.986125,0.598416,-0.548397,-0.481705,0.494090,0.378707,-0.481705,0.494090,0.378707
17583,770,3,0,5.087596,6.825460,6.463029,6.175867,3.433019,6.647688,1.386294,...,-0.915319,-3.276497,0.569163,-0.835044,-0.481705,0.494090,0.378707,-0.481705,0.494090,0.378707
17584,42,1,0,5.676754,8.495561,7.560601,6.985642,3.433019,3.761200,0.693147,...,0.578088,-1.731546,0.724809,0.690086,-0.964474,0.329254,-0.941672,-0.964474,0.329254,-0.941672
17585,20,0,0,5.501258,5.973810,5.771441,5.484797,3.258097,3.044522,0.000000,...,0.948881,-1.529157,0.745199,0.889879,-0.480836,0.494386,0.381083,-0.480836,0.494386,0.381083

In [25]:
df_model_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17586 entries, 0 to 17585
Data columns (total 78 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   views                        17586 non-null  int64
 1   likes                        17586 non-null  int64
 2   comments                     17586 non-null  int64
 3   duration_log                 17586 non-null  float64
 4   bitrate_log                  17586 non-null  float64
 5   height_log                   17586 non-null  float64
 6   width_log                    17586 non-null  float64
 7   frame rate_log               17586 non-null  float64
 8   views_log                    17586 non-null  float64
 9   likes_log                    17586 non-null  float64
 10  comments_log                 17586 non-null  float64
 11  likes_log_win                17586 non-null  float64
 12  comments_log_win             17586 non-null  float64
 13  duration_log_scaled          17586 non-null  float64
 14  duration_log_minmax          17586 non-null  float64
 15  duration_log_zscore          17586 non-null  float64
 16  height_log_scaled            17586 non-null  float64
 17  height_log_minmax            17586 non-null  float64
 18  height_log_zscore            17586 non-null  float64
 19  width_log_scaled             17586 non-null  float64
 20  width_log_minmax             17586 non-null  float64
 21  width_log_zscore             17586 non-null  float64
 22  frame rate_log_scaled        17586 non-null  float64
 23  frame rate_log_minmax        17586 non-null  float64
 24  frame rate_log_zscore        17586 non-null  float64
 25  views_log_scaled             17586 non-null  float64
 26  views_log_minmax             17586 non-null  float64
 27  views_log_zscore             17586 non-null  float64
 28  likes_log_scaled             17586 non-null  float64
 29  likes_log_minmax             17586 non-null  float64
 30  likes_log_zscore             17586 non-null  float64
 31  comments_log_scaled          17586 non-null  float64
 32  comments_log_minmax          17586 non-null  float64
 33  comments_log_zscore          17586 non-null  float64
 34  likes_log_win_scaled         17586 non-null  float64
 35  likes_log_win_minmax         17586 non-null  float64
 36  likes_log_win_zscore         17586 non-null  float64
 37  comments_log_win_scaled      17586 non-null  float64
 38  comments_log_win_minmax      17586 non-null  float64
 39  comments_log_win_zscore      17586 non-null  float64
 40  has_description              17586 non-null  int64
 41  has_hashtags                 17586 non-null  int64
 42  is_h264                      17586 non-null  int64
 43  cat_Comedy                   17586 non-null  bool
 44  cat_Education                17586 non-null  bool
 45  cat_Entertainment            17586 non-null  bool
 46  cat_Film & Animation         17586 non-null  bool
 47  cat_Gaming                   17586 non-null  bool
 48  cat_Howto & Style            17586 non-null  bool
 49  cat_Music                    17586 non-null  bool
 50  cat_News & Politics          17586 non-null  bool
 51  cat_Nonprofits & Activis     17586 non-null  bool
 52  cat_People & Blogs           17586 non-null  bool
 53  cat_Pets & Animals           17586 non-null  bool
 54  cat_Science & Technology     17586 non-null  bool
 55  cat_Shows                    17586 non-null  bool
 56  cat_Sports                   17586 non-null  bool
 57  cat_Travel & Events          17586 non-null  bool
 58  like_per_view_log            17586 non-null  float64
 59  comment_per_view_log         17586 non-null  float64
 60  engagement_rate_log          17586 non-null  float64
 61  aspect_ratio                 17586 non-null  float64
 62  log_aspect_ratio             17586 non-null  float64
 63  like_per_view_log_scaled     17586 non-null  float64
 64  like_per_view_log_minmax     17586 non-null  float64
 65  like_per_view_log_zscore     17586 non-null  float64
 66  comment_per_view_log_scaled  17417 non-null  float64
 67  comment_per_view_log_minmax  17586 non-null  float64
 68  comment_per_view_log_zscore  17586 non-null  float64
 69  engagement_rate_log_scaled   17586 non-null  float64
 70  engagement_rate_log_minmax   17586 non-null  float64
 71  engagement_rate_log_zscore   17586 non-null  float64
 72  aspect_ratio_scaled          17586 non-null  float64
 73  aspect_ratio_minmax          17586 non-null  float64
 74  aspect_ratio_zscore          17586 non-null  float64
 75  log_aspect_ratio_scaled      17586 non-null  float64
 76  log_aspect_ratio_minmax      17586 non-null  float64
 77  log_aspect_ratio_zscore      17586 non-null  float64
dtypes: bool(15), float64(57), int64(6)
memory usage: 8.7 MB

In [31]:
df_model_norm.to_csv("../data/youtube_modeling.csv")